import type { Aisle, CatalogEntry, Measure } from "./types";

type Extra = Partial<Omit<CatalogEntry, "id" | "aisle" | "measure" | "aliases">>;

function e(id: string, aisle: Aisle, measure: Measure, aliases: string, extra: Extra = {}): CatalogEntry {
  return {
    id,
    name: extra.name ?? id.replaceAll("-", " "),
    aliases: aliases ? aliases.split("|") : [],
    aisle,
    measure,
    ...extra,
  };
}

const P = "Produce";
const B = "Bakery";
const M = "Meat & Seafood";
const D = "Dairy & Eggs";
const T = "Pantry";
const S = "Spices";
const F = "Frozen";
const V = "Beverages";
const H = "Household";

const herb = (id: string, aliases: string, extra: Extra = {}): CatalogEntry =>
  e(id, P, "piece", aliases, { pieceUnit: "bunch", pieceGrams: 30, density: 0.1, unitGrams: { sprig: 3, handful: 15, leaf: 0.5, stalk: 3 }, ...extra });
const spice = (id: string, aliases: string, extra: Extra = {}): CatalogEntry =>
  e(id, S, "g", aliases, { staple: true, density: 0.5, ...extra });
const sauce = (id: string, aliases: string, extra: Extra = {}): CatalogEntry =>
  e(id, T, "ml", aliases, { staple: true, density: 1.1, ...extra });
const canned = (id: string, aliases: string, grams = 400, extra: Extra & { measure?: Measure } = {}): CatalogEntry =>
  e(id, T, extra.measure ?? "piece", aliases, { pieceUnit: "can", pieceGrams: grams, ...extra });

/**
 * The shared ingredient vocabulary. Every recipe line and every shopping item resolves to one of these.
 * Aliases are matched after normalisation and English singularisation, so list plurals only for German.
 * Order inside the file does not matter; longest alias match wins.
 */
export const CATALOG: readonly CatalogEntry[] = [
  // ─── Produce: vegetables ────────────────────────────────────────────────
  e("onion", P, "piece", "onions|yellow onion|brown onion|white onion|zwiebel|zwiebeln|gemüsezwiebel|speisezwiebel|minced onion", { pieceGrams: 150, density: 0.6 }),
  e("red-onion", P, "piece", "rote zwiebel|rote zwiebeln|purple onion", { pieceGrams: 150 }),
  e("shallot", P, "piece", "schalotte|schalotten", { pieceGrams: 30 }),
  e("spring-onion", P, "piece", "green onion|scallion|frühlingszwiebel|frühlingszwiebeln|lauchzwiebel|lauchzwiebeln|salad onion", { pieceGrams: 15, density: 0.25 }),
  e("leek", P, "piece", "lauch|porree", { pieceGrams: 200 }),
  e("garlic", P, "piece", "garlic clove|clove garlic|knoblauch|knoblauchzehe|knoblauchzehen|chopped garlic|lazy garlic|garlic head|head of garlic|knoblauchknolle|garlic paste", { pieceUnit: "clove", pieceGrams: 5, density: 0.6, unitGrams: { head: 50 } }),
  e("ginger", P, "g", "fresh ginger|ingwer|ginger root|knob of ginger|grated ginger|ginger paste|ingwerwurzel", { pieceGrams: 50, density: 1, unitGrams: { knob: 50, piece: 50 } }),
  e("ginger-garlic-paste", F, "piece", "ginger & garlic cube|ginger and garlic cube|ginger garlic cube|ginger garlic paste|garlic ginger paste|ingwer knoblauch paste|ingwer knoblauch würfel|garlic and ginger paste|ginger and garlic paste", { pieceUnit: "cube", pieceGrams: 15 }),
  e("vegetables", P, "g", "veg|green veg|mixed vegetables|gemüse|vegetable|veggies|greens|green vegetables|seasonal vegetables|stir fry vegetables|wok gemüse|stir fry veg|mixed veg|root vegetables|wurzelgemüse|suppengemüse|soup vegetables|salad vegetables", { generic: true, density: 0.5 }),
  e("tomato", P, "piece", "tomatoes|tomate|tomaten|vine tomato|strauchtomate|strauchtomaten|fleischtomate|fleischtomaten|beef tomato", { pieceGrams: 120 }),
  e("cherry-tomato", P, "g", "cherry tomatoes|baby tomato|plum tomato|cocktailtomate|cocktailtomaten|kirschtomate|kirschtomaten|datteltomate|datteltomaten|grape tomato|cherrytomaten", { pieceGrams: 15, density: 0.6 }),
  e("bell-pepper", P, "piece", "peppers|bell peppers|red pepper|green pepper|yellow pepper|orange pepper|mixed peppers|mixed bell peppers|capsicum|paprikaschote|paprikaschoten|rote paprika|gelbe paprika|grüne paprika|spitzpaprika|gemüsepaprika|sweet pepper|pointed pepper", { pieceGrams: 150 }),
  e("chili", P, "piece", "chilli|chile|fresh chili|red chili|green chili|chili pepper|chilli pepper|chilischote|chilischoten|jalapeño|jalapeno|jalapenos|birds eye chili|thai chili|peperoni|serrano pepper", { pieceGrams: 15 }),
  e("courgette", P, "piece", "zucchini|courgettes|zucchinis", { pieceGrams: 200 }),
  e("aubergine", P, "piece", "eggplant|asian eggplant|chinese eggplant|auberginen", { pieceGrams: 300 }),
  e("cucumber", P, "piece", "cucumbers|gurke|gurken|salatgurke|schlangengurke|persian cucumber", { pieceGrams: 400, density: 0.6 }),
  e("carrot", P, "piece", "carrots|karotte|karotten|möhre|möhren|rüebli|wurzel", { pieceGrams: 80, density: 0.5 }),
  e("celery", P, "piece", "celery stalk|sellerie|staudensellerie|stangensellerie|celery stick", { pieceUnit: "stalk", pieceGrams: 40 }),
  e("celeriac", P, "piece", "celery root|knollensellerie", { pieceGrams: 700 }),
  e("potato", P, "g", "potatoes|kartoffel|kartoffeln|baby potato|new potato|waxy potato|festkochende kartoffeln|mehlig kochende kartoffeln|drillinge", { pieceGrams: 150 }),
  e("sweet-potato", P, "piece", "sweet potatoes|süsskartoffel|süsskartoffeln|japanese sweet potato|yam", { pieceGrams: 250 }),
  e("pumpkin", P, "piece", "hokkaido|kürbis|hokkaido kürbis|hokkaidokürbis|butternut squash|butternut|squash|muskatkürbis|butternusskürbis", { pieceGrams: 1_000 }),
  e("broccoli", P, "piece", "brokkoli|broccoli floret|broccoli florets|broccolini|tenderstem broccoli", { pieceGrams: 400, density: 0.36 }),
  e("cauliflower", P, "piece", "blumenkohl|cauliflower floret", { pieceGrams: 800, density: 0.4 }),
  e("spinach", P, "g", "spinat|baby spinach|babyspinat|blattspinat|shredded spinach", { density: 0.13, pieceGrams: 100 }),
  e("kale", P, "g", "grünkohl|cavolo nero|curly kale", { density: 0.1 }),
  e("chard", P, "piece", "swiss chard|mangold", { pieceUnit: "bunch", pieceGrams: 300 }),
  e("lettuce", P, "piece", "salad|salat|kopfsalat|romaine|romaine lettuce|iceberg|iceberg lettuce|eisbergsalat|salad greens|mixed greens|mixed salad|little gem|shredded lettuce|blattsalat|römersalat|salad leaves|gemischter salat", { pieceUnit: "head", pieceGrams: 300, density: 0.2 }),
  e("rocket", P, "g", "arugula|rucola|rauke", { density: 0.1 }),
  e("cabbage", P, "piece", "kohl|weisskohl|white cabbage|red cabbage|rotkohl|blaukraut|spitzkohl|pointed cabbage|savoy cabbage|wirsing|chinakohl|napa cabbage|chinese cabbage|chinese leaf", { pieceGrams: 1_000 }),
  e("bok-choy", P, "piece", "pak choi|pak choy|baby bok choy|bok choi", { pieceGrams: 150 }),
  e("brussels-sprout", P, "g", "brussels sprouts|rosenkohl", { density: 0.55 }),
  e("mushroom", P, "g", "mushrooms|button mushroom|champignon|champignons|pilze|pilz|chestnut mushroom|portobello|shiitake|oyster mushroom|kräuterseitling|braune champignons|mixed mushrooms", { density: 0.35, pieceGrams: 20 }),
  e("avocado", P, "piece", "avocados|avocadoes", { pieceGrams: 200 }),
  e("corn-cob", P, "piece", "corn on the cob|maiskolben|sweetcorn cob|corn cob"),
  e("bean-sprout", P, "g", "bean sprouts|sprossen|mungbohnensprossen|mung bean sprouts|mungobohnensprossen|sojasprossen", { density: 0.45 }),
  e("green-bean", P, "g", "green beans|runner beans|runner bean|grüne bohnen|french beans|haricots verts|prinzessbohnen|brechbohnen|fine beans", { density: 0.45 }),
  e("pea", F, "g", "peas|erbsen|frozen peas|tk erbsen|garden peas|petits pois", { density: 0.65 }),
  e("edamame", F, "g", "edamame beans|soybeans|sojabohnen", { density: 0.65 }),
  e("sugar-snap", P, "g", "sugar snap peas|sugar snaps|zuckerschoten|mangetout|snow peas|kaiserschoten", { density: 0.4 }),
  e("asparagus", P, "g", "spargel|grüner spargel|green asparagus|white asparagus|weisser spargel", { density: 0.5, pieceGrams: 25 }),
  e("fennel", P, "piece", "fenchel|fennel bulb|fenchelknolle", { pieceGrams: 300 }),
  e("beetroot", P, "piece", "beets|beet|rote bete|rote beete|rote rüben", { pieceGrams: 150 }),
  e("radish", P, "piece", "radishes|radieschen", { pieceUnit: "bunch", pieceGrams: 150 }),
  e("turnip", P, "piece", "kohlrabi|swede|steckrübe|mairübe|rübe", { pieceGrams: 300 }),
  e("parsnip", P, "piece", "parsnips|pastinake|pastinaken", { pieceGrams: 150 }),
  e("artichoke", P, "piece", "artichokes|artischocke|artischocken", { pieceGrams: 300 }),
  e("lemongrass", P, "piece", "lemon grass|zitronengras", { pieceUnit: "stalk", pieceGrams: 15 }),
  e("kaffir-lime-leaf", P, "piece", "kaffir lime leaves|makrut lime leaves|limettenblätter", { pieceUnit: "leaf", pieceGrams: 1 }),
  e("galangal", P, "g", "galgant", { pieceGrams: 50 }),
  e("horseradish", P, "g", "meerrettich|fresh horseradish", { pieceGrams: 100 }),
  e("sprouts", P, "g", "cress|kresse|microgreens|alfalfa", { density: 0.1 }),

  // ─── Produce: fruit ─────────────────────────────────────────────────────
  e("lemon", P, "piece", "lemons|zitrone|zitronen|lemon juice|zitronensaft|lemon zest|zitronenschale|zitronenabrieb|juice of lemon|lemon wedge", { pieceGrams: 100, pieceMl: 45, density: 1 }),
  e("lime", P, "piece", "limes|limette|limetten|lime juice|limettensaft|lime zest|lime wedge|limettenschale", { pieceGrams: 70, pieceMl: 30, density: 1 }),
  e("orange", P, "piece", "oranges|orangen|orange zest|orangenschale|orange juice|orangensaft|blood orange", { pieceGrams: 200, pieceMl: 80, density: 1 }),
  e("apple", P, "piece", "apples|apfel|äpfel|granny smith|braeburn", { pieceGrams: 180 }),
  e("pear", P, "piece", "pears|birne|birnen", { pieceGrams: 180 }),
  e("banana", P, "piece", "bananas|banane|bananen", { pieceGrams: 120 }),
  e("strawberry", P, "g", "strawberries|erdbeere|erdbeeren", { density: 0.6 }),
  e("blueberry", P, "g", "blueberries|blaubeere|blaubeeren|heidelbeere|heidelbeeren", { density: 0.65 }),
  e("raspberry", P, "g", "raspberries|himbeere|himbeeren", { density: 0.5 }),
  e("berries", P, "g", "mixed berries|beeren|gemischte beeren|blackberries|blackberry|brombeeren|johannisbeeren|currants|red currants", { generic: true, density: 0.55 }),
  e("grape", P, "g", "grapes|trauben|weintrauben", { density: 0.65 }),
  e("peach", P, "piece", "peaches|pfirsich|pfirsiche|nectarine|nectarines|nektarine|nektarinen|apricot|apricots|aprikose|aprikosen", { pieceGrams: 150 }),
  e("plum", P, "piece", "plums|pflaume|pflaumen|zwetschge|zwetschgen", { pieceGrams: 60 }),
  e("cherry", P, "g", "cherries|kirsche|kirschen", { density: 0.65 }),
  e("mango", P, "piece", "mangos|mangoes", { pieceGrams: 350 }),
  e("pineapple", P, "piece", "ananas", { pieceGrams: 1_000 }),
  e("melon", P, "piece", "melone|watermelon|wassermelone|honeydew|honigmelone|cantaloupe|galia", { pieceGrams: 1_500 }),
  e("kiwi", P, "piece", "kiwis|kiwifruit", { pieceGrams: 75 }),
  e("pomegranate", P, "piece", "granatapfel|pomegranate seeds|granatapfelkerne", { pieceGrams: 250 }),
  e("fig", P, "piece", "figs|feige|feigen", { pieceGrams: 50 }),
  e("grapefruit", P, "piece", "pink grapefruit", { pieceGrams: 300 }),
  e("date", T, "g", "dates|dattel|datteln|medjool dates", { density: 0.7, pieceGrams: 8 }),
  e("raisin", T, "g", "raisins|rosine|rosinen|sultanas|sultanine|dried cranberries|cranberries|getrocknete cranberries", { density: 0.65 }),
  e("dried-fruit", T, "g", "dried apricots|getrocknete aprikosen|dried figs|dried mango|trockenfrüchte|trockenobst", { generic: true, density: 0.6 }),
  e("coconut", T, "g", "desiccated coconut|coconut flakes|shredded coconut|kokosraspel|kokosflocken|kokosnuss", { density: 0.35 }),

  // ─── Produce: fresh herbs ───────────────────────────────────────────────
  herb("parsley", "petersilie|flat leaf parsley|flatleaf parsley|italian parsley|glatte petersilie|krause petersilie|curly parsley"),
  herb("coriander-leaf", "cilantro|fresh coriander|coriander leaves|korianderblätter|frischer koriander|koriandergrün|coriander stalks", { name: "fresh coriander" }),
  herb("basil", "fresh basil|basilikum|thai basil|basil leaves|basilikumblätter|holy basil"),
  herb("mint", "fresh mint|minze|mint leaves|pfefferminze|minzblätter"),
  herb("dill", "fresh dill|dille"),
  herb("chive", "chives|schnittlauch"),
  herb("rosemary", "fresh rosemary|rosmarin|rosemary sprig|rosmarinzweig", { pieceUnit: "sprig", pieceGrams: 5 }),
  herb("thyme-fresh", "fresh thyme|thyme sprig|thyme sprigs|frischer thymian|thymianzweig|thymianzweige", { name: "fresh thyme", pieceUnit: "sprig", pieceGrams: 3 }),
  herb("sage", "fresh sage|salbei|sage leaves|salbeiblätter", { pieceUnit: "sprig", pieceGrams: 5 }),
  herb("tarragon", "estragon"),
  herb("marjoram-fresh", "fresh marjoram|majoran frisch|fresh oregano|frischer oregano", { name: "fresh oregano" }),
  herb("spring-herbs", "fresh herbs|frische kräuter|mixed fresh herbs|kräuter|herbs", { generic: true, name: "fresh herbs" }),

  // ─── Bakery ─────────────────────────────────────────────────────────────
  e("bread", B, "piece", "brot|crusty bread|loaf|loaf of bread|sourdough|sourdough bread|baguette|weissbrot|toast|toastbrot|ciabatta|vollkornbrot|graubrot|bauernbrot|sliced bread|rye bread|roggenbrot", { pieceGrams: 500, pieceUnit: undefined }),
  e("bread-roll", B, "piece", "bread rolls|rolls|brötchen|semmel|semmeln|buns|burger buns|burger bun|hot dog buns|brioche buns|weckle|schrippe|schrippen|dinner rolls|ciabatta rolls", { pieceGrams: 60 }),
  e("tortilla", B, "piece", "tortillas|wraps|wrap|large tortilla|flour tortilla|corn tortilla|gluten free tortilla|weizentortilla|weizentortillas|tortilla wraps|soft tacos|taco shells", { pieceGrams: 60 }),
  e("pita", B, "piece", "pitta|pita bread|pitta bread|fladenbrot|pide|pitas", { pieceGrams: 80 }),
  e("naan", B, "piece", "naan bread|naans|roti|chapati|chapatis", { pieceGrams: 90 }),
  e("croissant", B, "piece", "croissants", { pieceGrams: 60 }),
  e("bagel", B, "piece", "bagels", { pieceGrams: 90 }),
  e("pizza-base", B, "piece", "pizza dough|pizzateig|pizza bases|pizza crust|flatbread|flatbreads|pizza base", { pieceGrams: 250 }),
  e("cake", B, "piece", "kuchen|muffin|muffins|brownie|brownies|cookies|kekse|biscuits", { generic: true, pieceGrams: 80 }),

  // ─── Meat & Seafood ─────────────────────────────────────────────────────
  e("chicken-breast", M, "g", "chicken breasts|hähnchenbrust|hühnerbrust|hähnchenbrustfilet|hähnchenbrustfilets|chicken fillet|chicken breast fillet|chicken fillets|chicken breast fillets|hühnerbrustfilet|putenbrust|turkey breast", { pieceGrams: 200 }),
  e("chicken-thigh", M, "g", "chicken thighs|hähnchenschenkel|hähnchenkeule|hähnchenkeulen|chicken leg|chicken legs|chicken drumstick|chicken drumsticks|hähnchenoberschenkel|boneless chicken thighs|skin on chicken thighs", { pieceGrams: 150 }),
  e("chicken-wing", M, "g", "chicken wings|hähnchenflügel|wings", { pieceGrams: 90 }),
  e("chicken", M, "g", "whole chicken|hähnchen|huhn|hühnerfleisch|hühnchen|grilled chicken|cooked chicken|shredded chicken|chicken pieces|chicken meat|chicken strips|rotisserie chicken|poulet|hähnchenfleisch", { pieceGrams: 1_400, density: 0.6 }),
  e("chicken-sausage", M, "piece", "chicken sausages|hähnchenwurst|hähnchenwürstchen|turkey sausage|turkey sausages|geflügelwurst|geflügelwürstchen", { pieceGrams: 60 }),
  e("ground-beef", M, "g", "minced beef|beef mince|hackfleisch|rinderhack|rinderhackfleisch|lean ground beef|mince|minced meat|ground meat|hack|gemischtes hackfleisch|gemischtes hack|mixed mince|beef mince", { pieceGrams: 500 }),
  e("beef", M, "g", "rindfleisch|beef steak|steak|steaks|flank steak|sirloin|sirloin steak|rump steak|ribeye|rib eye|rinderfilet|beef fillet|beef strips|stewing beef|braising steak|rindergulasch|gulasch|beef chuck|chuck roast|beef brisket|brisket|entrecôte|entrecote|hüftsteak|rumpsteak|skirt steak|beef roast|roastbeef|rinderbraten|stir fry beef|beef shin|oxtail", { pieceGrams: 250 }),
  e("pork", M, "g", "schweinefleisch|pork loin|pork chop|pork chops|schweinekotelett|schweinekoteletts|pork tenderloin|schweinefilet|pork shoulder|schweineschulter|pork steak|schweinenacken|pork neck|schnitzel|pork fillet|pork mince|ground pork|schweinehack|minced pork|pulled pork|schweinebraten|pork roast|pork ribs|spare ribs|rippchen", { pieceGrams: 200 }),
  e("pork-belly", M, "g", "schweinebauch|skin on pork belly|pork belly slices|bauchfleisch", { pieceGrams: 500 }),
  e("bacon", M, "g", "bacon slices|speck|frühstücksspeck|streaky bacon|bauchspeck|bacon rashers|smoked bacon|räucherspeck|back bacon|cooked bacon|bacon bits|schinkenspeck|schinkenwürfel|speckwürfel|lardons", { pieceUnit: "slice", pieceGrams: 25 }),
  e("pancetta", M, "g", "guanciale|pancetta cubes", { pieceGrams: 100 }),
  e("chorizo", M, "g", "chorizo sausage", { pieceGrams: 200 }),
  e("sausage", M, "piece", "sausages|würstchen|wurst|bratwurst|bratwürste|italian sausage|sweet italian sausage|pork sausage|pork sausages|sausage meat|nürnberger|wiener|wiener würstchen|frankfurter|merguez|salsiccia|cumberland sausage|sausagemeat", { pieceGrams: 80 }),
  e("ham", M, "g", "schinken|kochschinken|prosciutto|parmaschinken|parma ham|serrano|serrano ham|sliced ham|honey ham|black forest ham|schwarzwälder schinken|gammon|ham hock|rohschinken|lachsschinken", { pieceUnit: "slice", pieceGrams: 25 }),
  e("salami", M, "g", "pepperoni|salami slices|cabanossi", { pieceUnit: "slice", pieceGrams: 5 }),
  e("lamb", M, "g", "lammfleisch|lamb chops|lamb chop|lammkotelett|lamb mince|ground lamb|lammhack|lamb shoulder|lamb leg|lammkeule|lamb shank|lammfilet|lamb steaks", { pieceGrams: 200 }),
  e("turkey", M, "g", "truthahn|pute|putenfleisch|turkey mince|ground turkey|putenhack|putenhackfleisch|turkey steaks|putenschnitzel|turkey thigh|putenkeule|putenschnitzel", { pieceGrams: 200 }),
  e("duck", M, "g", "ente|entenbrust|duck breast|duck breasts|duck legs|entenkeule|entenkeulen", { pieceGrams: 300 }),
  e("veal", M, "g", "kalbfleisch|veal cutlet|kalbsschnitzel|veal mince|kalbshack", { pieceGrams: 200 }),
  e("meatball", M, "piece", "meatballs|frikadellen|fleischbällchen|köttbullar|hackbällchen", { pieceGrams: 30 }),
  e("salmon", M, "g", "lachs|salmon fillet|salmon fillets|lachsfilet|lachsfilets|salmon steak|lachssteak|salmon side", { pieceUnit: "fillet", pieceGrams: 150 }),
  e("smoked-salmon", M, "g", "räucherlachs|graved lachs|gravlax|smoked trout|räucherforelle", { pieceGrams: 100 }),
  e("white-fish", M, "g", "cod|kabeljau|seelachs|alaska seelachs|haddock|schellfisch|pollock|pollack|hake|seehecht|tilapia|fish fillet|fish fillets|fischfilet|fischfilets|seelachsfilet|seelachsfilets|white fish fillets|rotbarsch|zander|dorade|sea bream|sea bass|wolfsbarsch|halibut|heilbutt|plaice|scholle|monkfish|coley|basa|fish|fisch|firm white fish", { pieceUnit: "fillet", pieceGrams: 150, name: "white fish" }),
  e("trout", M, "g", "forelle|forellen|rainbow trout|regenbogenforelle", { pieceGrams: 300 }),
  e("tuna-steak", M, "g", "fresh tuna|tuna steaks|thunfischsteak|thunfischsteaks|thunfischfilet", { name: "tuna steak", pieceGrams: 150 }),
  e("shrimp", M, "g", "prawns|prawn|shrimps|garnelen|garnele|king prawns|riesengarnelen|uncooked shrimp|raw prawns|tiger prawns|crevetten|scampi|jumbo shrimp|cooked prawns", { pieceGrams: 15, density: 0.6 }),
  e("squid", M, "g", "tintenfisch|calamari|octopus|oktopus|pulpo|squid rings|calamares", { pieceGrams: 200 }),
  e("mussel", M, "g", "mussels|muscheln|miesmuscheln|clams|venusmuscheln|scallops|jakobsmuscheln|scallop", { pieceGrams: 20 }),
  e("crab", M, "g", "crab meat|krebsfleisch|krabben|nordseekrabben|lobster|hummer|surimi", { pieceGrams: 100 }),
  e("tofu", D, "g", "extra firm tofu|firm tofu|silken tofu|räuchertofu|smoked tofu|tofu block|bean curd", { pieceUnit: "block", pieceGrams: 400, density: 1 }),
  e("tempeh", D, "g", "seitan|meat substitute|fleischersatz|vegan mince|soja hack|sojahack|vegetarian sausages|vegetarische würstchen|plant based mince|veggie mince", { generic: true, pieceGrams: 200 }),

  // ─── Dairy & Eggs ───────────────────────────────────────────────────────
  e("egg", D, "piece", "eggs|ei|eier|large egg|whole egg|whole eggs|egg white|egg whites|eiweiss|egg yolk|egg yolks|eigelb|medium egg|fried egg|fried eggs|boiled egg|soft boiled eggs|hühnerei|hühnereier|free range eggs", { pieceGrams: 55, pieceMl: 50 }),
  e("milk", D, "ml", "milch|whole milk|vollmilch|semi skimmed milk|skimmed milk|fettarme milch|frischmilch|h milch|dairy milk", { density: 1.03, pieceMl: 1_000 }),
  e("cream", D, "ml", "heavy cream|double cream|whipping cream|sahne|schlagsahne|single cream|pouring cream|heavy whipping cream|schlagobers|rahm|kochsahne|cooking cream", { density: 1, pieceMl: 200 }),
  e("sour-cream", D, "g", "saure sahne|schmand|soured cream|sauerrahm", { density: 1, pieceGrams: 200 }),
  e("creme-fraiche", D, "g", "crème fraîche|creme fraiche|crème fraiche", { name: "crème fraîche", density: 1, pieceGrams: 200 }),
  e("yogurt", D, "g", "yoghurt|greek yogurt|greek yoghurt|joghurt|griechischer joghurt|natural yogurt|natural yoghurt|naturjoghurt|plain yogurt|fat free greek yogurt|low fat greek yoghurt|skyr|sahnejoghurt|coconut yogurt|kokosjoghurt|soy yogurt|sojajoghurt", { density: 1.03, pieceGrams: 150 }),
  e("quark", D, "g", "magerquark|speisequark|cottage cheese|hüttenkäse|fromage frais|topfen", { density: 1, pieceGrams: 250 }),
  e("butter", D, "g", "unsalted butter|salted butter|ghee|süssrahmbutter|butterschmalz|clarified butter", { density: 0.911, pieceGrams: 250 }),
  e("margarine", D, "g", "vegan butter|plant butter|pflanzenmargarine", { density: 0.9, pieceGrams: 250 }),
  e("cream-cheese", D, "g", "frischkäse|low fat cream cheese|philadelphia|kräuterfrischkäse|doppelrahmfrischkäse|light cream cheese|mascarpone", { density: 1, pieceGrams: 200 }),
  e("cheese", D, "g", "käse|grated cheese|shredded cheese|light cheese|low fat grated cheese|reibekäse|gouda|emmentaler|emmental|edam|edamer|bergkäse|butterkäse|gruyère|gruyere|comté|comte|swiss cheese|monterey jack|pepper jack|mexican cheese|cheese slices|käsescheiben|streukäse|pizzakäse|pizza cheese|raclette|raclette cheese|manchego|provolone|fontina|hard cheese|hartkäse|schnittkäse|appenzeller|tilsiter|leerdammer|maasdamer|mixed cheese", { density: 0.4, pieceGrams: 200 }),
  e("cheddar", D, "g", "light cheddar|mature cheddar|red leicester|cheddar cheese|shredded cheddar|grated cheddar", { density: 0.4, pieceGrams: 200 }),
  e("mozzarella", D, "g", "light mozzarella|mozzarella cheese|fresh mozzarella|burrata|büffelmozzarella|buffalo mozzarella|mozzarella ball|mozzarella balls|grated mozzarella|shredded mozzarella", { density: 0.4, pieceGrams: 125 }),
  e("parmesan", D, "g", "parmesan cheese|parmigiano|parmigiano reggiano|pecorino|pecorino romano|grated parmesan|grana padano|parmesankäse|freshly grated parmesan|shaved parmesan|parmesan shavings", { density: 0.42, pieceGrams: 200 }),
  e("feta", D, "g", "feta cheese|feta light|block of feta|schafskäse|hirtenkäse|feta block", { density: 0.9, pieceGrams: 200 }),
  e("halloumi", D, "g", "halloumi cheese|grillkäse|grill cheese|paneer", { pieceGrams: 225 }),
  e("blue-cheese", D, "g", "gorgonzola|roquefort|stilton|blauschimmelkäse|crumbled blue cheese|danish blue|dolcelatte", { density: 0.5, pieceGrams: 150 }),
  e("goat-cheese", D, "g", "goats cheese|ziegenkäse|chèvre|chevre|ziegenfrischkäse|goat cheese log", { density: 0.9, pieceGrams: 150 }),
  e("ricotta", D, "g", "ricotta cheese", { density: 1, pieceGrams: 250 }),
  e("brie", D, "g", "camembert|brie cheese|weichkäse|soft cheese", { pieceGrams: 200 }),
  e("gnocchi", D, "g", "potato gnocchi|kartoffelgnocchi|gnocchis", { pieceGrams: 500 }),
  e("fresh-pasta", D, "g", "fresh pasta|frische pasta|fresh ravioli|ravioli|tortellini|fresh tortellini|frische tortellini|fresh lasagne sheets|fresh tagliatelle|maultaschen|spätzle|schupfnudeln", { generic: true, name: "fresh pasta", pieceGrams: 250 }),
  e("puff-pastry", D, "piece", "blätterteig|ready rolled puff pastry|shortcrust pastry|mürbeteig|filo pastry|filo|yufka|pie crust|pastry|pastry sheet|flammkuchenteig|croissant dough|quiche dough|strudelteig", { generic: true, pieceUnit: "sheet", pieceGrams: 275 }),
  e("hummus", D, "g", "houmous|humus", { pieceGrams: 200 }),
  e("oat-milk", V, "ml", "hafermilch|oat drink|haferdrink|almond milk|mandelmilch|soy milk|sojamilch|plant milk|pflanzenmilch|pflanzendrink|rice milk|cashew milk|coconut drink", { name: "plant milk", density: 1.03, pieceMl: 1_000 }),

  // ─── Pantry: canned & jarred ────────────────────────────────────────────
  canned("canned-tomato", "chopped tomatoes|crushed tomatoes|canned tomatoes|tinned tomatoes|diced tomatoes|can of tomatoes|tin of tomatoes|gehackte tomaten|dosentomaten|stückige tomaten|tomaten aus der dose|whole peeled tomatoes|plum tomatoes canned|san marzano tomatoes|chopped tomato|tomato tin|tomatoes in juice|geschälte tomaten|pizzatomaten", 400, { name: "canned tomatoes", density: 1 }),
  e("tomato-paste", T, "g", "tomatenmark|tomato purée|tomato puree|concentrated tomato paste|doppelt konzentriertes tomatenmark", { density: 1.1, pieceGrams: 200, pieceUnit: "tube", staple: true }),
  e("passata", T, "ml", "tomato passata|passierte tomaten|tomato sauce|tomato pasta sauce|pasta sauce|tomatensauce|tomatensosse|marinara|marinara sauce|pizza sauce|pizzasauce|jar of pasta sauce|sugo|tomato pizza sauce|strained tomatoes|canned tomato sauce|tomato sauce can", { density: 1.05, pieceMl: 500, pieceUnit: "jar" }),
  e("sundried-tomato", T, "g", "sun dried tomatoes|sundried tomatoes|getrocknete tomaten|sonnengetrocknete tomaten|sundried tomato hearts|semi dried tomatoes", { density: 0.6, pieceGrams: 100 }),
  canned("chickpea", "chickpeas|kichererbsen|garbanzo beans|garbanzo|can of chickpeas|tin of chickpeas", 400),
  canned("black-bean", "black beans|schwarze bohnen|tin black beans|can black beans", 400),
  canned("kidney-bean", "kidney beans|kidneybohnen|red kidney beans|rote bohnen", 400),
  canned("white-bean", "cannellini beans|cannellini|butter beans|weisse bohnen|haricot beans|navy beans|borlotti beans|lima beans|pinto beans|great northern beans|beans|bohnen|mixed beans|baked beans", 400),
  canned("sweetcorn", "corn|sweet corn|mais|zuckermais|tinned corn|canned corn|dosenmais|corn kernels|frozen corn", 300),
  canned("coconut-milk", "kokosmilch|light coconut milk|coconut cream|kokoscreme|kokosnussmilch|can coconut milk|tin coconut milk|full fat coconut milk", 400, { measure: "ml", pieceMl: 400, density: 1 }),
  canned("tuna", "tinned tuna|canned tuna|thunfisch|thunfisch aus der dose|tuna in oil|tuna in water|tuna can|can of tuna|tuna flakes", 150),
  canned("anchovy", "anchovies|anchovy fillets|sardellen|sardellenfilets|sardines|sardinen|mackerel tin|makrele", 50),
  e("olive", T, "g", "olives|oliven|black olives|green olives|schwarze oliven|grüne oliven|kalamata olives|kalamata|pitted olives", { density: 0.6, pieceGrams: 150, pieceUnit: "jar" }),
  e("caper", T, "g", "capers|kapern", { density: 0.6, pieceGrams: 100, pieceUnit: "jar", staple: true }),
  e("pickle", T, "g", "pickles|gherkins|gewürzgurken|essiggurken|cornichons|dill pickles|pickled cucumber|saure gurken|pickled onions|silberzwiebeln", { pieceGrams: 350, pieceUnit: "jar" }),
  e("pickled-ginger", T, "g", "sushi ginger|beni shoga|gari|eingelegter ingwer|japanese pickled ginger|red pickled ginger", { density: 1, pieceGrams: 100, pieceUnit: "jar" }),
  e("kimchi", T, "g", "sauerkraut|kraut", { pieceGrams: 400, pieceUnit: "jar" }),
  e("jalapeno-pickled", T, "g", "pickled jalapeños|pickled jalapenos|eingelegte jalapeños|jalapeños aus dem glas|jalapenos jar", { name: "pickled jalapeños", pieceGrams: 200, pieceUnit: "jar" }),
  e("roasted-pepper", T, "g", "roasted peppers|roasted red peppers|gegrillte paprika|geröstete paprika|piquillo peppers|jarred peppers|antipasti", { name: "roasted peppers", pieceGrams: 300, pieceUnit: "jar" }),
  e("artichoke-heart", T, "g", "artichoke hearts|artischockenherzen|marinated artichokes", { name: "artichoke hearts", pieceGrams: 280, pieceUnit: "jar" }),
  e("seaweed", T, "piece", "nori|nori sheets|seaweed flakes|seaweed snack|seasoned seaweed|algen|algenblätter|sushi nori|wakame|kombu|kelp", { pieceUnit: "packet", pieceGrams: 10 }),
  e("apple-sauce", T, "g", "applesauce|apfelmus|apfelkompott|compote|kompott", { name: "apple sauce", pieceGrams: 350, pieceUnit: "jar" }),
  e("jam", T, "g", "marmelade|marmalade|konfitüre|preserves|strawberry jam|erdbeermarmelade|apricot jam|aprikosenmarmelade|fruit spread|fruchtaufstrich", { pieceGrams: 350, pieceUnit: "jar" }),
  e("chocolate-spread", T, "g", "nutella|nut nougat spread|nussnougatcreme|hazelnut spread|schokocreme", { pieceGrams: 400, pieceUnit: "jar" }),
  e("peanut-butter", T, "g", "erdnussbutter|creamy peanut butter|crunchy peanut butter|erdnussmus|almond butter|mandelmus|cashew butter|nut butter|tahini|sesame paste|sesammus", { density: 1.05, pieceGrams: 350, pieceUnit: "jar", staple: true }),

  // ─── Pantry: dry goods ──────────────────────────────────────────────────
  e("rice", T, "g", "reis|white rice|jasmine rice|jasminreis|basmati|basmati rice|basmatireis|short grain rice|long grain rice|langkornreis|uncooked rice|cooked rice|sushi rice|sushireis|risotto rice|arborio|arborio rice|carnaroli|risottoreis|brown rice|vollkornreis|naturreis|wild rice|paella rice|parboiled rice|sticky rice|klebreis|milchreis|pudding rice|day old rice|rundkornreis|short grain white rice|cooked and cooled rice", { density: 0.85, pieceGrams: 1_000, staple: true }),
  e("rice-noodle", T, "g", "rice noodles|flat rice noodles|vermicelli rice noodles|rice vermicelli|reisnudeln|glass noodles|glasnudeln|pad thai noodles|rice stick noodles|vermicelli", { pieceGrams: 250 }),
  e("noodle", T, "g", "noodles|egg noodles|eiernudeln|ramen|ramen noodles|udon|udon noodles|soba|soba noodles|mie nudeln|mie noodles|instant noodles|asian noodles|asia nudeln|wok noodles|chow mein noodles|lo mein noodles|instant ramen", { pieceGrams: 250 }),
  e("pasta", T, "g", "spaghetti|penne|fusilli|tagliatelle|linguine|orzo|orzo pasta|lasagne sheets|lasagna sheets|lasagna noodles|lasagne|lasagneplatten|macaroni|makkaroni|rigatoni|farfalle|nudeln|pappardelle|fettuccine|conchiglie|tortiglioni|bucatini|vermicelli pasta|dried pasta|uncooked pasta|pasta shapes|short pasta|penne rigate|shells|pasta shells|ditalini|cavatappi|risoni|kritharaki|spaghettini|capellini|angel hair|whole wheat pasta|vollkornnudeln|elbow macaroni|gluten free pasta|bandnudeln|hörnchennudeln|spirelli|dried spaghetti|dried tagliatelle", { pieceGrams: 20, pieceUnit: "sheet", density: 0.5, staple: true }),
  e("couscous", T, "g", "bulgur|quinoa|freekeh|pearl barley|perlgraupen|graupen|millet|hirse|buckwheat|buchweizen|polenta|maisgriess|semolina|grits|farro|dinkel|spelt|hartweizengriess", { generic: true, density: 0.7, pieceGrams: 500 }),
  e("oats", T, "g", "rolled oats|haferflocken|porridge oats|oatmeal|jumbo oats|zarte haferflocken|kernige haferflocken|quick oats|steel cut oats|oat flour|hafermehl|muesli|müsli|granola|cereal|cornflakes|frühstücksflocken", { density: 0.4, pieceGrams: 500, staple: true }),
  e("breadcrumb", T, "g", "breadcrumbs|bread crumbs|panko|panko breadcrumbs|paniermehl|semmelbrösel|brösel|croutons|stuffing mix", { density: 0.45, pieceGrams: 400, staple: true }),
  e("flour", T, "g", "all purpose flour|plain flour|mehl|weizenmehl|type 405|type 550|whole wheat flour|wholemeal flour|vollkornmehl|bread flour|strong flour|self raising flour|self rising flour|spelt flour|dinkelmehl|00 flour|tipo 00|cake flour|rye flour|roggenmehl|gluten free flour|glutenfreies mehl|almond flour|mandelmehl|chickpea flour|kichererbsenmehl|rice flour|reismehl|coconut flour|buckwheat flour|wheat flour|potato flour", { density: 0.53, pieceGrams: 1_000, staple: true }),
  e("cornstarch", T, "g", "corn starch|cornflour|corn flour|speisestärke|maisstärke|stärke|potato starch|kartoffelstärke|tapioca starch|arrowroot|mondamin|starch|thickener", { density: 0.55, pieceGrams: 400, staple: true }),
  e("baking-powder", T, "g", "backpulver|baking soda|bicarbonate of soda|bicarb|natron|cream of tartar|weinstein", { density: 0.9, pieceGrams: 15, pieceUnit: "packet", staple: true }),
  e("yeast", T, "g", "hefe|trockenhefe|dry yeast|instant yeast|active dry yeast|fresh yeast|frische hefe|sourdough starter", { density: 0.7, pieceGrams: 7, pieceUnit: "packet", staple: true }),
  e("sugar", T, "g", "white sugar|granulated sugar|zucker|caster sugar|superfine sugar|feiner zucker|haushaltszucker|cane sugar|rohrzucker|raw sugar|rohrohrzucker|golden sugar|sweetener|süssstoff|erythrit|xylit|stevia|coconut sugar|kokosblütenzucker|palm sugar|palmzucker|jaggery|gelierzucker", { density: 0.85, pieceGrams: 1_000, staple: true }),
  e("brown-sugar", T, "g", "brauner zucker|light brown sugar|dark brown sugar|soft brown sugar|muscovado|demerara|muscovado sugar", { density: 0.93, pieceGrams: 500, staple: true }),
  e("icing-sugar", T, "g", "puderzucker|powdered sugar|confectioners sugar", { density: 0.56, pieceGrams: 250, staple: true }),
  e("honey", T, "ml", "honig|runny honey|clear honey|raw honey|agave|agave syrup|agavendicksaft|agave nectar|golden syrup|zuckerrübensirup|sirup", { density: 1.42, pieceMl: 350, pieceUnit: "jar", staple: true }),
  e("maple-syrup", T, "ml", "ahornsirup|pure maple syrup|date syrup|dattelsirup|pancake syrup", { density: 1.32, pieceMl: 250, pieceUnit: "bottle", staple: true }),
  e("vanilla", T, "ml", "vanilla extract|vanilleextrakt|vanille|vanilla essence|vanilla bean|vanilla pod|vanilleschote|vanilla paste|vanillezucker|vanilla sugar|vanillin", { density: 0.9, staple: true }),
  e("cocoa", T, "g", "cocoa powder|kakao|kakaopulver|backkakao|unsweetened cocoa|dutch process cocoa|cacao|drinking chocolate|hot chocolate|kakao pulver", { density: 0.36, pieceGrams: 250, staple: true }),
  e("chocolate", T, "g", "schokolade|dark chocolate|zartbitterschokolade|dunkle schokolade|milk chocolate|vollmilchschokolade|white chocolate|weisse schokolade|chocolate chips|schokodrops|schokotropfen|chocolate chunks|couverture|kuvertüre|baking chocolate|cooking chocolate|chocolate bar|schokoriegel|bittersweet chocolate|semisweet chocolate|semi sweet chocolate chips", { density: 0.65, pieceGrams: 100 }),
  e("gelatin", T, "g", "gelatine|gelatin sheets|gelatine blätter|agar agar|agar", { pieceGrams: 2, pieceUnit: "sheet", staple: true }),
  e("custard-powder", T, "g", "puddingpulver|vanillepuddingpulver|custard|instant pudding|jelly|jello|götterspeise|tortenguss", { pieceGrams: 40, pieceUnit: "packet" }),
  e("condensed-milk", T, "ml", "sweetened condensed milk|gezuckerte kondensmilch|kondensmilch|evaporated milk|dulce de leche|karamellcreme", { density: 1.3, pieceMl: 400, pieceUnit: "can" }),
  e("peanut", T, "g", "peanuts|erdnüsse|erdnuss|dry roasted peanuts|salted peanuts|gesalzene erdnüsse|roasted peanuts|erdnusskerne", { density: 0.6, pieceGrams: 200 }),
  e("cashew", T, "g", "cashews|cashewkerne|cashew nuts|cashewnüsse|raw cashews", { density: 0.55, pieceGrams: 200 }),
  e("almond", T, "g", "almonds|mandeln|mandel|ground almonds|gemahlene mandeln|flaked almonds|almond flakes|mandelblättchen|slivered almonds|gehobelte mandeln|blanched almonds|almond slivers|toasted almonds|marzipan|marzipanrohmasse", { density: 0.6, pieceGrams: 200 }),
  e("walnut", T, "g", "walnuts|walnüsse|walnusskerne|walnut halves|pecans|pecan|pecan nuts|pekannüsse", { density: 0.5, pieceGrams: 200 }),
  e("pine-nut", T, "g", "pine nuts|pinienkerne", { density: 0.6, pieceGrams: 100 }),
  e("hazelnut", T, "g", "hazelnuts|haselnüsse|haselnusskerne|ground hazelnuts|gemahlene haselnüsse|macadamia|macadamia nuts|brazil nuts|paranüsse|mixed nuts|gemischte nüsse|nüsse|nuts|chopped nuts", { generic: true, density: 0.6, pieceGrams: 200 }),
  e("pistachio", T, "g", "pistachios|pistazien|pistazienkerne|shelled pistachios", { density: 0.55, pieceGrams: 100 }),
  e("sesame-seed", T, "g", "sesame seeds|sesame|sesam|toasted sesame seeds|geröstete sesamsamen|sesamsamen|black sesame|schwarzer sesam|white sesame seeds|sesame seed", { density: 0.6, pieceGrams: 100, staple: true }),
  e("seeds", T, "g", "pumpkin seeds|kürbiskerne|sunflower seeds|sonnenblumenkerne|chia seeds|chiasamen|chia|flaxseed|flax seeds|leinsamen|hemp seeds|hanfsamen|mixed seeds|poppy seeds|mohn|mohnsamen|nigella seeds|black onion seeds|schwarzkümmel", { generic: true, name: "seeds", density: 0.6, pieceGrams: 200 }),
  e("tortilla-chip", T, "g", "tortilla chips|nachos|nacho chips|corn chips|maischips|chips|crisps|kartoffelchips|potato chips|pretzels|brezeln|salzstangen|popcorn|snacks|crackers|cracker|knäckebrot|rice cakes|reiswaffeln|salted crackers|ritz crackers|graham crackers|digestive biscuits|löffelbiskuit|ladyfingers|butterkekse", { generic: true, name: "tortilla chips", pieceGrams: 200, pieceUnit: "bag", density: 0.15 }),
  e("stock-cube", T, "piece", "stock cubes|brühwürfel|bouillon cube|bouillon cubes|bouillon powder|chicken bouillon powder|chicken bouillon|hühnerbrühe pulver|gemüsebrühe pulver|gemüsebrühpulver|better than bouillon|stock powder|instant stock|brühe pulver|stock pot|stock pots|gemüsebrühwürfel|hühnerbrühwürfel|rinderbrühwürfel|bouillon|dashi|dashi powder|dashi stock|instant brühe", { generic: true, pieceUnit: "cube", pieceGrams: 10, staple: true }),
  e("chicken-stock", T, "ml", "chicken broth|hühnerbrühe|hühnerfond|geflügelbrühe|geflügelfond|chicken stock cube|chicken stock cubes|low sodium chicken broth|chicken bone broth", { staple: true, density: 1, pieceMl: 500 }),
  e("vegetable-stock", T, "ml", "vegetable broth|gemüsebrühe|gemüsefond|veg stock|veggie stock|vegetable stock cube|vegetable bouillon", { staple: true, density: 1, pieceMl: 500 }),
  e("beef-stock", T, "ml", "beef broth|rinderbrühe|rinderfond|beef stock cube|beef bouillon|bone broth|fischfond|fish stock|fish broth|fond|lamb stock", { staple: true, density: 1, pieceMl: 500 }),
  e("stock", T, "ml", "broth|brühe|stock cube|stockcube|stock or water|water or stock", { staple: true, density: 1, pieceMl: 500 }),
  e("lentil", T, "g", "lentils|linsen|red lentils|red split lentils|rote linsen|green lentils|grüne linsen|brown lentils|puy lentils|beluga lentils|beluga linsen|yellow lentils|gelbe linsen|split peas|schälerbsen|dried chickpeas|getrocknete kichererbsen|dried beans|getrocknete bohnen|mung beans|mungbohnen|black lentils|urad dal|dal|dhal|chana dal|moong dal", { density: 0.8, pieceGrams: 500 }),
  e("gravy", T, "g", "gravy granules|bratensauce|bratensosse|instant gravy|sossenbinder|sauce thickener|gravy mix|bratenfond", { pieceGrams: 200, staple: true }),

  // ─── Pantry: oils, vinegars, condiments, sauces ─────────────────────────
  e("olive-oil", T, "ml", "olivenöl|extra virgin olive oil|evoo|olive oil spray|natives olivenöl|natives olivenöl extra|good olive oil|extra virgin oil", { staple: true, density: 0.91, pieceMl: 500, pieceUnit: "bottle" }),
  e("vegetable-oil", T, "ml", "oil|öl|neutral oil|neutral tasting oil|neutral flavoured oil|vegetable oil|pflanzenöl|rapeseed oil|rapsöl|canola oil|canola|sunflower oil|sonnenblumenöl|grape seed oil|grapeseed oil|traubenkernöl|cooking oil|frying oil|frittieröl|bratöl|peanut oil|erdnussöl|corn oil|avocado oil|neutral cooking oil|oil spray|cooking spray|oil for frying|öl zum braten|öl zum frittieren|oil for cooking", { staple: true, density: 0.92, pieceMl: 1_000, pieceUnit: "bottle" }),
  e("sesame-oil", T, "ml", "toasted sesame oil|sesamöl|geröstetes sesamöl|dark sesame oil", { staple: true, density: 0.92, pieceMl: 250, pieceUnit: "bottle" }),
  e("coconut-oil", T, "ml", "kokosöl|kokosfett|coconut butter", { staple: true, density: 0.92, pieceMl: 400, pieceUnit: "jar" }),
  e("chili-oil", T, "ml", "chilli oil|chiliöl|crispy chili oil|chili crisp|chilli crisp|hot oil|lao gan ma", { staple: true, density: 0.92, pieceMl: 200, pieceUnit: "jar" }),
  e("vinegar", T, "ml", "essig|white wine vinegar|weissweinessig|red wine vinegar|rotweinessig|apple cider vinegar|apfelessig|cider vinegar|white vinegar|weisser essig|distilled vinegar|malt vinegar|sherry vinegar|sherryessig|wine vinegar|weinessig|tafelessig|branntweinessig|champagne vinegar", { staple: true, density: 1.01, pieceMl: 500, pieceUnit: "bottle" }),
  e("rice-vinegar", T, "ml", "reisessig|rice wine vinegar|seasoned rice vinegar|sushi vinegar|sushi essig|black vinegar|chinkiang vinegar|chinese black vinegar", { staple: true, density: 1.01, pieceMl: 250, pieceUnit: "bottle" }),
  e("balsamic", T, "ml", "balsamic vinegar|balsamico|aceto balsamico|balsamic glaze|balsamico creme|balsamessig|white balsamic|weisser balsamico|crema di balsamico", { name: "balsamic vinegar", staple: true, density: 1.06, pieceMl: 250, pieceUnit: "bottle" }),
  sauce("soy-sauce", "soja sauce|sojasauce|sojasosse|low sodium soy sauce|dark soy sauce|light soy sauce|tamari|shoyu|reduced sodium soy sauce|all purpose soy sauce|kikkoman|coconut aminos|liquid aminos|dunkle sojasauce|helle sojasauce|sweet soy sauce|kecap manis|ketjap manis", { density: 1.15, pieceMl: 250, pieceUnit: "bottle" }),
  sauce("fish-sauce", "fischsauce|fischsosse|nam pla|nuoc mam|thai fish sauce", { density: 1.2, pieceMl: 200, pieceUnit: "bottle" }),
  sauce("oyster-sauce", "austernsauce|austernsosse|vegetarian oyster sauce|mushroom stir fry sauce", { pieceMl: 250, pieceUnit: "bottle" }),
  sauce("hoisin", "hoisin sauce|hoisinsauce|hoisin sosse|char siu sauce|plum sauce|pflaumensauce", { name: "hoisin sauce", pieceMl: 250, pieceUnit: "jar" }),
  sauce("hot-sauce", "sriracha|sriracha hot sauce|chili sauce|chilli sauce|chilisauce|chilisosse|tabasco|franks hot sauce|buffalo sauce|sambal|sambal oelek|sweet chili sauce|sweet chilli sauce|süsse chilisauce|garlic chili sauce|chili garlic sauce|cholula|hot pepper sauce|piri piri sauce|peri peri sauce|thai chili sauce|nam prik|sriracha sauce", { generic: true, density: 1.05, pieceMl: 250, pieceUnit: "bottle" }),
  sauce("worcestershire-sauce", "worcester sauce|worcestersauce|worcestershiresauce|worcester sosse", { pieceMl: 150, pieceUnit: "bottle" }),
  sauce("mirin", "sake|cooking sake|reiswein|rice wine|shaoxing wine|shaoxing|chinese cooking wine|chinese rice wine|shao hsing|dry sherry|sherry|marsala|kochwein|cooking wine|vermouth|port|portwein|madeira", { generic: true, name: "mirin / rice wine", density: 1.1, pieceMl: 250, pieceUnit: "bottle" }),
  e("miso", T, "g", "miso paste|misopaste|white miso|red miso|shiro miso|aka miso|gochujang|korean chili paste|korean chilli paste|chili paste|chilli paste|chilipaste|doenjang|ssamjang|doubanjiang|chili bean paste|toban djan|black bean paste|black bean sauce|fermented black beans|douchi|gochujang paste", { generic: true, name: "miso / chili paste", staple: true, density: 1.15, pieceGrams: 300, pieceUnit: "tube" }),
  e("chipotle-paste", T, "g", "chipotle chilli paste|chipotle chili paste|chipotle paste|chipotles in adobo|chipotle in adobo|adobo sauce|chipotle peppers|chipotle|harissa|harissa paste|ajvar|red pepper paste|smoky tomato paste|smoky tomato|nduja|calabrian chili paste", { generic: true, name: "chipotle / harissa paste", staple: true, density: 1.1, pieceGrams: 200, pieceUnit: "jar" }),
  e("curry-paste", T, "g", "red curry paste|green curry paste|yellow curry paste|thai curry paste|currypaste|rote currypaste|grüne currypaste|massaman paste|panang paste|laksa paste|tikka masala paste|tandoori paste|madras paste|korma paste|rendang paste|tom yum paste|patak", { generic: true, staple: true, density: 1.1, pieceGrams: 200, pieceUnit: "jar" }),
  e("peanut-sauce", T, "ml", "satay sauce|sataysauce|erdnusssauce|erdnusssosse|thai peanut sauce|peanut dressing|satay marinade", { density: 1.1, pieceMl: 250, pieceUnit: "jar" }),
  e("barbecue-sauce", T, "ml", "bbq sauce|barbecue sosse|barbecuesauce|japanese barbecue sauce|bachans|yakiniku sauce|teriyaki|teriyaki sauce|teriyakisauce|bulgogi sauce|bulgogi marinade|steak sauce|hp sauce|brown sauce|yakitori sauce|tonkatsu sauce|katsu sauce|okonomiyaki sauce|unagi sauce|eel sauce|ponzu|ponzu sauce|stir fry sauce|sweet and sour sauce|black bean stir fry sauce|general tso sauce|orange sauce", { generic: true, density: 1.15, pieceMl: 300, pieceUnit: "bottle" }),
  e("ketchup", T, "ml", "tomato ketchup|tomatenketchup|catsup|curry ketchup", { staple: true, density: 1.15, pieceMl: 500, pieceUnit: "bottle" }),
  e("mustard", T, "g", "dijon mustard|dijon|senf|mittelscharfer senf|medium hot mustard|wholegrain mustard|körniger senf|english mustard|yellow mustard|american mustard|honey mustard|honigsenf|brown mustard|mustard powder|senfpulver|hot mustard|scharfer senf|süsser senf|sweet mustard|dijon senf|grainy mustard|dijon or medium hot mustard", { staple: true, density: 1.05, pieceGrams: 200, pieceUnit: "jar" }),
  e("mayo", T, "g", "mayonnaise|mayonaise|light mayonnaise|light mayo|vegan mayo|kewpie|kewpie mayo|japanese mayo|japanese mayonnaise|aioli|garlic mayo|remoulade|tartar sauce|tartare sauce|salatmayonnaise|joghurt mayonnaise|miracle whip|ranch|ranch dressing|caesar dressing|salad dressing|dressing|salatdressing|vinaigrette|blue cheese dressing|thousand island|salad cream|burger sauce|joppiesaus|frittensauce|cocktailsauce|tzatziki|raita", { generic: true, name: "mayonnaise", density: 0.95, pieceGrams: 250, pieceUnit: "jar" }),
  e("pesto", T, "g", "green pesto|basil pesto|red pesto|pesto rosso|pesto genovese|pesto verde|grünes pesto|rotes pesto|sun dried tomato pesto|pesto alla genovese|jar of pesto|vegan pesto|kale pesto|pesto sauce", { density: 1, pieceGrams: 190, pieceUnit: "jar" }),
  e("tamarind", T, "g", "tamarind paste|tamarind concentrate|tamarinde|tamarindenpaste|tamarind puree", { staple: true, density: 1.2, pieceGrams: 200, pieceUnit: "jar" }),
  e("wasabi", T, "g", "wasabi paste|wasabipaste|wasabi powder|horseradish sauce|meerrettich sauce|meerrettichsauce|creamed horseradish", { staple: true, pieceGrams: 40, pieceUnit: "tube" }),
  e("coconut-water", V, "ml", "kokoswasser|coconut juice", { density: 1, pieceMl: 330, pieceUnit: "bottle" }),
  e("taco-seasoning", S, "piece", "taco seasoning mix|taco mix|taco spice mix|taco gewürz|taco gewürzmischung|taco spice|fajita seasoning|fajita seasoning packet|fajita mix|fajita spice|fajita spice mix|fajita gewürz|burrito seasoning|chili seasoning mix|mexican seasoning|tex mex seasoning|enchilada seasoning|old el paso|seasoning packet|seasoning mix|gewürzmischung|spice mix|spice blend|seasoning blend|dry rub|bbq rub|barbecue rub|steak seasoning|chicken seasoning|cajun seasoning|cajun spice|creole seasoning|jerk seasoning|shawarma seasoning|shawarma spice|kebab seasoning|gyros gewürz|gyros seasoning|pizza seasoning|pizzagewürz|ranch seasoning|everything bagel seasoning|lemon pepper seasoning|lemon pepper|greek seasoning|mediterranean seasoning|italian seasoning mix|poultry seasoning|all purpose seasoning|seasoning salt|seasoned salt|gewürzsalz|adobo seasoning|sazon", { generic: true, name: "seasoning mix", pieceUnit: "packet", pieceGrams: 30 }),

  // ─── Spices & dried herbs (staples) ─────────────────────────────────────
  spice("salt", "kosher salt|sea salt|fine sea salt|salz|meersalz|table salt|flaky salt|flaked sea salt|fleur de sel|maldon|coarse salt|grobes salz|rock salt|steinsalz|himalayan salt|celtic salt|fine salt|feines salz|salt flakes|salz aus der mühle|salt to taste|iodised salt|jodsalz|pickling salt|kochsalz|speisesalz|salt water|salted water", { density: 1.2 }),
  spice("pepper", "black pepper|ground black pepper|white pepper|pfeffer|schwarzer pfeffer|weisser pfeffer|freshly ground pepper|freshly ground black pepper|cracked black pepper|peppercorns|black peppercorns|schwarze pfefferkörner|pfefferkörner|ground pepper|pepper to taste|fresh pepper|mixed peppercorns|bunter pfeffer|pfeffer aus der mühle|coarse black pepper|schwarzer pfeffer aus der mühle|pfeffer aus der mühle|white peppercorns|cracked pepper|pepper corn|black pepper corn|pepper mill", { density: 0.55 }),
  spice("chili-flakes", "chili flake|chilli flakes|chilliflakes|red pepper flakes|crushed red pepper|crushed red pepper flakes|chiliflocken|chili flocken|red chilli flakes|dried chili flakes|dried chilli flakes|gochugaru|korean chili flakes|korean chilli flakes|korean chili pepper flakes|korean red pepper flakes|aleppo pepper|pul biber|pul biber flakes|urfa biber|red chili flakes|chile flakes|hot pepper flakes|dried chilies|dried chillies|dried chili|dried chilli|getrocknete chili|getrocknete chilis|getrocknete chilischoten|chili de arbol|chiles de arbol|dried red chilies|dried red chillies|whole dried chilies|whole dried chillies|birdseye chilli dried", { name: "chili flakes", density: 0.35 }),
  spice("paprika", "smoked paprika|paprikapulver|paprika powder|sweet paprika|sweet smoked paprika|hot paprika|geräuchertes paprikapulver|paprika edelsüss|edelsüss|rosenpaprika|paprika rosenscharf|hungarian paprika|spanish paprika|pimentón|pimenton|smoked paprika powder|paprika geräuchert|paprika pulver|paprika spice|geräucherte paprika|paprikagewürz|smoky paprika|mild paprika|delicate paprika", { density: 0.45 }),
  spice("cumin", "kreuzkümmel|ground cumin|cumin seeds|cumin seed|kreuzkümmelsamen|gemahlener kreuzkümmel|jeera|whole cumin|cumin powder|comino", { density: 0.5 }),
  spice("coriander-seed", "ground coriander|coriander seeds|coriander seed|korianderpulver|gemahlener koriander|koriandersamen|koriander|coriander|coriander powder|dried coriander|korianderkörner|coriander ground", { name: "ground coriander", density: 0.4 }),
  spice("turmeric", "kurkuma|ground turmeric|turmeric powder|kurkumapulver|haldi|gelbwurz", { density: 0.55 }),
  spice("garam-masala", "curry powder|currypulver|curry|curry pulver|madras curry powder|mild curry powder|hot curry powder|tandoori masala|tandoori spice|tikka masala spice|chaat masala|biryani masala|ras el hanout|baharat|berbere|dukkah|za atar|zaatar|zatar|sumac|sumach|panch phoron|kashmiri chili powder|kashmiri chilli powder|amchur|asafoetida|hing|fenugreek|methi|kasuri methi|fenugreek leaves|fenugreek seeds|bockshornklee|ajwain|nigella|kalonji|mustard seeds|senfkörner|black mustard seeds|yellow mustard seeds|brown mustard seeds|curry leaves|curryblätter|garam masala powder|curry spice|curry gewürz|japanese curry roux|curry roux|golden curry", { generic: true, name: "garam masala / curry powder", density: 0.5 }),
  spice("cinnamon", "zimt|ground cinnamon|cinnamon stick|cinnamon sticks|zimtstange|zimtstangen|cinnamon powder|zimtpulver|ceylon cinnamon|cassia|cassia bark|cinnamon bark|small cinnamon stick", { density: 0.55 }),
  spice("star-anise", "sternanis|whole star anise|star anise pods|anise|anis|aniseed|anissamen|fennel seeds|fennel seed|fenchelsamen|fenchel samen|caraway|caraway seeds|kümmel|kümmelsamen|dill seeds|dillsamen|celery seed|celery seeds|selleriesamen|liquorice root|licorice root|süssholz", { generic: true, name: "star anise / whole spices", density: 0.4 }),
  spice("bay-leaf", "bay|bay leaves|lorbeer|lorbeerblatt|lorbeerblätter|dried bay leaves|bay leaf dried|fresh bay leaves|indian bay leaves|tej patta", { name: "bay leaves", density: 0.2 }),
  spice("nutmeg", "muskat|muskatnuss|ground nutmeg|whole nutmeg|mace|muskatblüte|allspice|piment|allspice berries|ground allspice|cloves|whole cloves|ground cloves|nelken|gewürznelken|cardamom|kardamom|cardamom pods|green cardamom|black cardamom|kardamomkapseln|ground cardamom|ginger powder|ground ginger|ingwerpulver|dried ginger|mixed spice|pumpkin pie spice|lebkuchengewürz|gingerbread spice|spekulatiusgewürz|chinese five spice|five spice|five spice powder|fünf gewürze pulver|apple pie spice|chai spice|mulling spices|glühweingewürz|juniper berries|wacholderbeeren|sichuan pepper|sichuan peppercorns|szechuan pepper|szechuan peppercorns|szechuanpfeffer|sichuanpfeffer|pink pepper|pink peppercorns|rosa beeren|saffron|safran|saffron threads|safranfäden|tonka bean|tonkabohne|rose water|rosenwasser|orange blossom water|orangenblütenwasser", { generic: true, name: "nutmeg / baking spices", density: 0.5 }),
  spice("garlic-powder", "knoblauchpulver|garlic granules|knoblauchgranulat|granulated garlic|dried garlic|garlic salt|knoblauchsalz|garlic flakes|knoblauchflocken|onion powder|zwiebelpulver|onion granules|zwiebelgranulat|dried onion|dried onion flakes|onion salt|zwiebelsalz|onion flakes|minced dried onion|garlic and onion powder|garlic onion powder", { name: "garlic / onion powder", density: 0.5 }),
  spice("dried-herbs", "italian seasoning|italian herbs|italienische kräuter|mixed herbs|mixed dried herbs|dried herbs|kräuter der provence|herbes de provence|herbs de provence|dried oregano|oregano|getrockneter oregano|dried thyme|thyme|thymian|getrockneter thymian|dried basil|dried basil leaves|getrocknetes basilikum|dried rosemary|getrockneter rosmarin|dried parsley|getrocknete petersilie|dried dill|dried marjoram|marjoram|majoran|dried sage|dried tarragon|dried mint|dried chives|8 kräuter|kräutermischung|herb mix|herb blend|pizza herbs|pizzakräuter|tuscan herbs|greek herbs|griechische kräuter|italian herb blend|dried italian herbs|dried mixed herbs|bouquet garni|fines herbes|savory|bohnenkraut|lovage|liebstöckel|maggikraut", { generic: true, name: "dried herbs", density: 0.2 }),
  spice("chili-powder", "chilipulver|chilli powder|cayenne|cayenne pepper|cayennepfeffer|ground chili|ground chilli|hot chili powder|mild chili powder|ancho chili powder|ancho powder|chipotle powder|chipotle chili powder|chipotle chilli powder|smoked chili powder|smoked chilli powder|red chili powder|red chilli powder|deggi mirch|lal mirch|chilli pulver|chili pulver|ground red pepper|ground cayenne|guajillo powder|korean chili powder|korean chilli powder|piment d espelette|espelette|urfa pepper|chili seasoning|chilli seasoning|chile powder|chili con carne gewürz|chili gewürz", { generic: true, name: "chili powder", density: 0.45 }),
  spice("spices", "spice|gewürze|gewürz|seasoning|seasonings|mixed spices|assorted spices|various spices|spices to taste|gewürze nach geschmack|all spices|other spices|spices of your choice|your favourite spices|your favorite spices|spice of choice|spices of choice", { generic: true, name: "spices", density: 0.5 }),
  spice("msg", "monosodium glutamate|umami seasoning|umami powder|glutamat|mushroom seasoning|mushroom powder|pilzpulver|chicken powder|hondashi|ajinomoto|umami paste|marmite|vegemite|yeast extract|hefeextrakt|nutritional yeast|hefeflocken|liquid smoke|flüssigrauch|maggi|maggi seasoning|maggi würze|gravy browning|browning sauce|bovril", { generic: true, name: "umami seasoning", density: 0.8 }),

  // ─── Frozen ─────────────────────────────────────────────────────────────
  e("frozen-spinach", F, "g", "tk spinat|tiefkühlspinat|rahmspinat|blattspinat tk|frozen chopped spinach|frozen leaf spinach", { name: "frozen spinach", pieceGrams: 450, pieceUnit: "packet" }),
  e("frozen-berries", F, "g", "frozen berries|tk beeren|tiefkühlbeeren|frozen mixed berries|frozen fruit|tk obst|frozen raspberries|tk himbeeren|frozen blueberries|tk blaubeeren|frozen strawberries|tk erdbeeren|frozen mango|tk mango|frozen cherries|tk kirschen|frozen banana|frozen bananas|frozen pineapple|frozen peaches|frozen fruit mix", { name: "frozen berries", density: 0.6, pieceGrams: 500, pieceUnit: "bag" }),
  e("frozen-vegetables", F, "g", "frozen vegetables|tk gemüse|tiefkühlgemüse|frozen mixed vegetables|mixed frozen vegetables|frozen veg|frozen stir fry vegetables|frozen broccoli|tk brokkoli|frozen cauliflower|tk blumenkohl|frozen green beans|tk bohnen|frozen carrots|frozen sweetcorn|frozen corn kernels|frozen onions|frozen diced onions|frozen peppers|frozen sliced peppers|frozen mixed peppers|frozen soffritto|frozen butternut squash|frozen cauliflower rice|frozen brussels sprouts|frozen kale|frozen mushrooms|frozen edamame|frozen wok vegetables|tk wokgemüse|kaisergemüse|frozen mixed veg|frozen vegetable mix|frozen veggies", { generic: true, name: "frozen vegetables", density: 0.6, pieceGrams: 750, pieceUnit: "bag" }),
  e("ice-cream", F, "ml", "eis|eiscreme|vanilla ice cream|vanilleeis|gelato|sorbet|frozen yogurt|frozen yoghurt|ice lollies|ice lolly|popsicles|popsicle|ice pops|eis am stiel|magnum|ben and jerrys|cornetto|soft serve|ice cream cones|eiswaffeln|ice cream cone|mochi ice cream|frozen dessert", { generic: true, name: "ice cream", density: 0.55, pieceMl: 500, pieceUnit: "pot" }),
  e("frozen-fries", F, "g", "frozen fries|frozen chips|oven chips|pommes|pommes frites|tk pommes|backofenpommes|french fries|fries|sweet potato fries|süsskartoffelpommes|potato wedges|kartoffelwedges|hash browns|rösti|kroketten|croquettes|tater tots|kartoffelpuffer|frozen pizza|tiefkühlpizza|tk pizza|garlic bread|knoblauchbrot|aufbackbrötchen|aufbackbaguette|spring rolls|frühlingsrollen|samosas|gyoza|dumplings|frozen dumplings|wontons|bao buns|dim sum|chicken nuggets|nuggets|hähnchennuggets|fish fingers|fischstäbchen|fish sticks|fish cakes|breaded fish|veggie burgers|burger patties|frozen burgers|falafel|frozen meatballs|ready meal|frozen ready meal|frozen lasagne|frozen pie|frozen herbs|frozen prawns|tk garnelen|frozen fish|frozen salmon|frozen cod", { generic: true, name: "frozen fries / frozen foods", pieceGrams: 750, pieceUnit: "bag" }),

  // ─── Beverages ──────────────────────────────────────────────────────────
  e("water", V, "ml", "hot water|cold water|warm water|boiling water|wasser|heisses wasser|kaltes wasser|lukewarm water|ice water|ice cubes|ice|eiswürfel|tap water|filtered water|water for boiling|water for cooking|water as needed|water to cover|water to thin|splash of water|extra water|more water|additional water|soaking water|reserved pasta water|pasta water|cooking water|pasta cooking water|reserved cooking water", { skip: true, density: 1 }),
  e("sparkling-water", V, "ml", "mineralwasser|mineral water|sprudel|sprudelwasser|soda water|club soda|seltzer|selters|tonic|tonic water|bottled water|stilles wasser|still water|sparkling mineral water|fizzy water|carbonated water|san pellegrino|perrier|apollinaris|gerolsteiner|volvic|evian|vittel", { name: "mineral water", pieceMl: 1_000, pieceUnit: "bottle" }),
  e("juice", V, "ml", "saft|apple juice|apfelsaft|fruit juice|fruchtsaft|multivitaminsaft|cranberry juice|cranberrysaft|pineapple juice|ananassaft|tomato juice|tomatensaft|grape juice|traubensaft|pomegranate juice|granatapfelsaft|mango juice|mangosaft|passion fruit juice|maracujasaft|cherry juice|kirschsaft|carrot juice|karottensaft|vegetable juice|gemüsesaft|smoothie|smoothies|apfelschorle|schorle|saftschorle|juice box|lemonade|limonade|iced tea|eistee|ice tea|cordial", { generic: true, pieceMl: 1_000, pieceUnit: "bottle" }),
  e("coffee", V, "g", "kaffee|ground coffee|kaffeepulver|coffee beans|kaffeebohnen|instant coffee|instantkaffee|espresso|espresso beans|espressobohnen|coffee pods|kaffeekapseln|coffee capsules|nespresso|nespresso pods|nespresso kapseln|dolce gusto|tassimo|coffee filters|kaffeefilter|filter coffee|filterkaffee|decaf|decaf coffee|cold brew|espresso powder|instant espresso|instant espresso powder|espressopulver|coffee creamer|kaffeesahne|coffee syrup", { generic: true, pieceGrams: 500, pieceUnit: "packet" }),
  e("tea", V, "piece", "tee|tea bags|teebeutel|green tea|grüner tee|black tea|schwarzer tee|herbal tea|kräutertee|chamomile tea|kamillentee|peppermint tea|pfefferminztee|mint tea|fruit tea|früchtetee|rooibos|earl grey|english breakfast|chai|chai tea|matcha|matcha powder|jasmine tea|oolong|white tea|ginger tea|ingwertee|fennel tea|fencheltee|loose tea|loose leaf tea|tea leaves|hot chocolate mix|chai latte", { generic: true, pieceGrams: 2, pieceUnit: "packet" }),
  e("beer", V, "ml", "bier|lager|pils|pilsner|weissbier|weizen|weizenbier|hefeweizen|wheat beer|ale|pale ale|ipa|stout|guinness|radler|alkoholfreies bier|non alcoholic beer|alcohol free beer|cider|apfelwein|hard cider|helles|kölsch|craft beer|light beer|mexican beer|corona|heineken|becks|krombacher|bitburger|paulaner|erdinger|augustiner|warsteiner|jever|kasten bier|beer crate|dosenbier|flaschenbier", { generic: true, pieceMl: 500, pieceUnit: "bottle" }),
  e("wine", V, "ml", "wein|white wine|weisswein|red wine|rotwein|dry white wine|trockener weisswein|dry red wine|trockener rotwein|rosé|rose wine|roséwein|prosecco|sekt|champagne|champagner|cava|sparkling wine|schaumwein|crémant|riesling|pinot grigio|grauburgunder|chardonnay|sauvignon blanc|pinot noir|spätburgunder|merlot|cabernet sauvignon|shiraz|syrah|malbec|rioja|chianti|primitivo|tempranillo|grüner veltliner|dornfelder|lambrusco|dessert wine|mulled wine|glühwein|sangria|cooking wine|white wine or stock|white wine or broth|non alcoholic wine|alkoholfreier wein|bottle of wine|bottle of white wine|bottle of red wine|flasche wein", { generic: true, pieceMl: 750, pieceUnit: "bottle" }),
  e("spirits", V, "ml", "vodka|wodka|gin|rum|whisky|whiskey|bourbon|scotch|tequila|brandy|cognac|weinbrand|grappa|ouzo|amaretto|limoncello|baileys|kahlua|cointreau|triple sec|campari|aperol|martini|bitters|angostura|schnapps|schnaps|kirschwasser|jägermeister|likör|liqueur|dark rum|white rum|spiced rum", { generic: true, pieceMl: 700, pieceUnit: "bottle" }),
  e("soft-drink", V, "ml", "cola|coke|coca cola|pepsi|diet coke|coke zero|cola zero|fanta|sprite|7up|mezzo mix|spezi|dr pepper|ginger ale|ginger beer|root beer|orangina|fizzy drink|fizzy drinks|soda|sodas|soft drinks|softdrinks|erfrischungsgetränke|energy drink|energy drinks|red bull|gatorade|isotonic drink|sports drink|kombucha|kefir|ayran|fritz kola|club mate|bionade|almdudler|schweppes|bitter lemon|tonic water|tonic", { generic: true, pieceMl: 1_500, pieceUnit: "bottle" }),

  // ─── Household ──────────────────────────────────────────────────────────
  e("toilet-paper", H, "piece", "toilettenpapier|klopapier|loo roll|loo rolls|toilet roll|toilet rolls|toilet tissue|bathroom tissue|wc papier|feuchtes toilettenpapier|moist toilet tissue", { pieceUnit: "packet" }),
  e("kitchen-roll", H, "piece", "paper towels|paper towel|küchenrolle|küchenpapier|küchenkrepp|kitchen paper|kitchen towel|kitchen towels|zewa", { pieceUnit: "packet" }),
  e("tissue", H, "piece", "tissues|taschentücher|kleenex|tempo|facial tissues|servietten|napkins|paper napkins|papierservietten", { pieceUnit: "packet" }),
  e("dish-soap", H, "piece", "spülmittel|washing up liquid|dishwashing liquid|dish liquid|fairy|fairy liquid|pril|geschirrspülmittel|handspülmittel|dish detergent", { pieceUnit: "bottle" }),
  e("dishwasher-tablets", H, "piece", "spülmaschinentabs|geschirrspültabs|dishwasher tabs|dishwasher pods|dishwasher detergent|finish tabs|somat|somat tabs|finish|spülmaschinen tabs|geschirrspüler tabs|dishwasher salt|spülmaschinensalz|regeneriersalz|rinse aid|klarspüler|dishwasher cleaner|maschinenreiniger|spülmaschinenreiniger", { pieceUnit: "packet" }),
  e("laundry-detergent", H, "piece", "waschmittel|washing powder|laundry powder|laundry liquid|waschpulver|flüssigwaschmittel|vollwaschmittel|colorwaschmittel|feinwaschmittel|wollwaschmittel|laundry pods|waschmittel pods|persil|ariel|lenor|softener|fabric softener|weichspüler|fabric conditioner|stain remover|fleckentferner|vanish|oxi action|bleach|bleiche|chlorine bleach|chlorbleiche|laundry sanitiser|hygienespüler|dryer sheets|trocknertücher|dryer balls|trocknerbälle|colour catcher|farbfangtücher|color catcher|wool wash|delicates wash|sport wash|sportwaschmittel|baby detergent|babywaschmittel|sensitive detergent|sensitiv waschmittel|eco detergent|ökowaschmittel|washing capsules|waschkapseln|laundry sheets|waschstreifen|laundry strips|waschblätter|laundry soap|waschseife|gallseife|gall soap|soap nuts|waschnüsse", { pieceUnit: "packet" }),
  e("bin-bag", H, "piece", "bin bags|müllbeutel|müllsäcke|müllsack|trash bags|garbage bags|rubbish bags|bin liners|bin liner|gelbe säcke|gelber sack|biomüllbeutel|compost bags|kompostbeutel|food waste bags|freezer bags|gefrierbeutel|tiefkühlbeutel|ziplock bags|zip bags|sandwich bags|food bags|resealable bags|dog poo bags|hundekotbeutel|nappy bags|windelbeutel", { generic: true, name: "bin bags", pieceUnit: "packet" }),
  e("foil", H, "piece", "aluminium foil|aluminum foil|alufolie|tin foil|kitchen foil|cling film|frischhaltefolie|plastic wrap|saran wrap|cling wrap|baking paper|backpapier|parchment paper|parchment|greaseproof paper|butterbrotpapier|wax paper|muffin cases|muffinförmchen|cupcake cases|cupcake liners|papierförmchen|toothpicks|zahnstocher|cocktail sticks|straws|strohhalme|trinkhalme|skewers|spiesse|holzspiesse|wooden skewers|bamboo skewers|kitchen string|küchengarn|kitchen twine|butchers twine|bratenschnur", { generic: true, name: "foil / baking paper", pieceUnit: "packet" }),
  e("sponge", H, "piece", "sponges|schwämme|schwamm|scourer|scourers|topfreiniger|spülschwamm|spülschwämme|dish brush|spülbürste|dish cloth|dish cloths|spültuch|spültücher|cleaning cloths|putzlappen|microfibre cloths|mikrofasertücher|microfiber cloths|tea towels|geschirrtücher|tea towel|geschirrtuch|rubber gloves|gummihandschuhe|cleaning gloves|putzhandschuhe|disposable gloves|einweghandschuhe|steel wool|stahlwolle|magic eraser|schmutzradierer", { generic: true, pieceUnit: "packet" }),
  e("cleaner", H, "piece", "allzweckreiniger|all purpose cleaner|multi surface cleaner|cleaning spray|reinigungsspray|kitchen cleaner|küchenreiniger|bathroom cleaner|badreiniger|toilet cleaner|wc reiniger|toilettenreiniger|glass cleaner|glasreiniger|window cleaner|fensterreiniger|floor cleaner|bodenreiniger|disinfectant|desinfektionsmittel|antibacterial wipes|desinfektionstücher|cleaning wipes|reinigungstücher|limescale remover|kalkreiniger|descaler|entkalker|drain cleaner|rohrreiniger|oven cleaner|backofenreiniger|stainless steel cleaner|edelstahlreiniger|air freshener|lufterfrischer|candles|kerzen|tea lights|teelichter|matches|streichhölzer|lighter|feuerzeug|charcoal|holzkohle|grillkohle|firelighters|grillanzünder", { generic: true, name: "cleaning products", pieceUnit: "bottle" }),
  e("soap", H, "piece", "seife|hand soap|handseife|liquid soap|flüssigseife|soap bar|shower gel|duschgel|body wash|shampoo|conditioner|spülung|body lotion|hand cream|handcreme|face cream|moisturiser|moisturizer|sunscreen|sonnencreme|sun cream|deodorant|deo|toothpaste|zahnpasta|zahncreme|toothbrush|zahnbürste|toothbrushes|mouthwash|mundspülung|dental floss|zahnseide|razor|rasierer|razors|rasierklingen|razor blades|shaving foam|rasierschaum|cotton pads|wattepads|cotton buds|wattestäbchen|wet wipes|feuchttücher|baby wipes|nappies|windeln|diapers|pampers|sanitary towels|binden|sanitary pads|tampons|panty liners|slipeinlagen|make up remover", { generic: true, name: "soap / toiletries", pieceUnit: "bottle" }),
  e("battery", H, "piece", "batteries|batterien|batterie|aa batteries|aaa batteries|aa batterien|aaa batterien|9v battery|button batteries|knopfzellen|rechargeable batteries|akkus|light bulb|light bulbs|glühbirne|glühbirnen|led bulb|led bulbs|leuchtmittel|fuses|sicherungen|extension lead|verlängerungskabel|usb cable|usb kabel|charging cable|ladekabel|charger|ladegerät|printer paper|druckerpapier|printer ink|druckerpatronen|ink cartridges|tintenpatronen|pens|stifte|pen|kugelschreiber|pencils|bleistifte|markers|marker|glue|kleber|glue stick|klebestift|tape|klebeband|sellotape|tesa|post its|haftnotizen|sticky notes|envelopes|briefumschläge|stamps|briefmarken|birthday card|geburtstagskarte|wrapping paper|geschenkpapier|balloons|luftballons|birthday candles|geburtstagskerzen|paper plates|pappteller|paper cups|pappbecher|napkins|servietten|flowers|blumen|bouquet|blumenstrauss|potting soil|blumenerde|plant food|pflanzendünger", { generic: true, name: "batteries / bulbs / stationery", pieceUnit: "packet" }),
  e("pet-food", H, "piece", "dog food|hundefutter|cat food|katzenfutter|dry dog food|dry cat food|trockenfutter|wet dog food|wet cat food|nassfutter|cat litter|katzenstreu|litter|streu|dog treats|hundeleckerli|cat treats|katzenleckerli|treats|leckerli|dog biscuits|hundekekse|dental sticks|dentastix|chews|kauknochen|bird seed|vogelfutter|bird food|fish food|fischfutter|hamster food|rabbit food|kaninchenfutter|hay|heu|bedding|einstreu|poo bags|kotbeutel|puppy pads|flea treatment|flohmittel|worming tablets|wurmkur", { generic: true, name: "pet food / supplies", pieceUnit: "packet" }),
];

export const CATALOG_BY_ID: ReadonlyMap<string, CatalogEntry> = new Map(CATALOG.map((entry) => [entry.id, entry]));
